#!/bin/bash 
​
​
#variables 
nums=$(echo {0..9})
states=('Nebraska' 'Hawaii' 'Texas' 'Illinois')
ls_out=$(ls)
​
for num in ${nums[@]};
do 
	if [ $num = 3 ] || [ $num = 5 ] || [ $num = 7 ]
	then
		echo $num 
	fi 
done 
​
​
​
​
for state in ${states[@]};
do 
	if [ $state == 'Hawaii' ];
	then 
		echo "Hawaii is the best!" 
	else 
		echo "Im not a fan of Hawaii."
	fi 
done 
​
​
​
for x in ${ls_out[@]};
do 
	echo $x
done
